# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-31 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
