# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-01 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_profile_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='projects',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
