# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-01 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='owner_profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
